import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["200", "500", "800"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "GrowUpAI",
  description: "Generated by GrowUpAI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable}`}
      suppressHydrationWarning
    >
      <body className="bg-white text-black dark:bg-gray-950 dark:text-white transition-colors duration-300">
        {children}
      </body>
    </html>
  );
}
