import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/contexts/authContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  weight: ["200", "500", "800"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "GrowUpAI",
  description: "Generated by GrowUpAI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable}`} suppressHydrationWarning>
      <AuthProvider>
        <body className="bg-gray-50 text-black dark:bg-gray-950 dark:text-white transition-colors duration-300">
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 2000,
              style: {
                background: "#fff",
                color: "#363636",
              },
            }}
          />
        </body>
      </AuthProvider>
    </html>
  );
}
